apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecommerce-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pkarthick83/ecommerce:backend_latest
        imagePullPolicy: Always
        env:
          - name: DB_HOST
            value: postgres   # Service name for Postgres in the same namespace
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ecommerce-secret
                key: DB_PASSWORD
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
