apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: ecommerce
data:
  db-init.sql: |
    CREATE TABLE IF NOT EXISTS products (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100),
      price NUMERIC(10, 2)
    );

    CREATE TABLE IF NOT EXISTS orders (
      id SERIAL PRIMARY KEY,
      product_id INT REFERENCES products(id),
      quantity INT,
      total NUMERIC(10, 2)
    );

    INSERT INTO products (name, price) VALUES
      ('Laptop', 999.99),
      ('Smartphone', 699.99),
      ('Headphones', 199.99)
    ON CONFLICT DO NOTHING;

    INSERT INTO orders (product_id, quantity, total) VALUES
      (1, 1, 999.99),
      (2, 2, 1399.98)
    ON CONFLICT DO NOTHING;
